# Generated by Django 4.0.4 on 2022-06-16 13:44

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_case_type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chipset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Chipset', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_color', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection_standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_standard', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Heatsink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heatsink_type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mainboard_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_form', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_manufacturer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Memory_Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_standard', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Available_Quantity', models.IntegerField(default=0)),
                ('Warranty_Period', models.IntegerField(blank=True, null=True)),
                ('Origin', models.CharField(blank=True, max_length=50, null=True)),
                ('src_img', models.ImageField(blank=True, null=True, upload_to=product.models.upload_to, verbose_name='Image')),
                ('price', models.FloatField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PSU_Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAM_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socket_CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_socket', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CASE_Cover',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('name_case_cover', models.CharField(max_length=255, unique=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('rgb', models.BooleanField(blank=True, null=True)),
                ('case_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.casetype')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.colors')),
            ],
        ),
        migrations.CreateModel(
            name='Radiator',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('name_radiator', models.CharField(max_length=255, unique=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('wattage', models.FloatField(blank=True, null=True)),
                ('Speed', models.IntegerField(blank=True, null=True)),
                ('rgb', models.BooleanField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('heatsink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.heatsink')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_type'),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_gpu', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='CPU_Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_series', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='CPU_Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_generation', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='VGA',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('name_vga', models.CharField(max_length=255, unique=True)),
                ('capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('oc_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('gaming_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('memory_bus', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_processing_units', models.IntegerField(blank=True, null=True)),
                ('radiators', models.CharField(blank=True, max_length=255, null=True)),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.gpu')),
                ('memory_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.memory_standard')),
            ],
        ),
        migrations.CreateModel(
            name='Socket_Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket_cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.socket_cpu')),
                ('radiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.radiator')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('name_ram', models.CharField(max_length=255, unique=True)),
                ('capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('quantity_in_pack', models.IntegerField(blank=True, null=True)),
                ('rbg', models.BooleanField(blank=True, default=False)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('ram_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ram_type')),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('name_psu', models.CharField(max_length=255, unique=True)),
                ('psu_wattage', models.CharField(blank=True, max_length=50, null=True)),
                ('psu_input_power', models.CharField(blank=True, max_length=50, null=True)),
                ('cooling_fan_size', models.CharField(blank=True, max_length=255, null=True)),
                ('psu_performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.psu_performance')),
            ],
        ),
        migrations.CreateModel(
            name='Mainboard_Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainboard_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mainboard_form')),
                ('case_cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.case_cover')),
            ],
        ),
        migrations.CreateModel(
            name='Mainboard',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('name_mainboard', models.CharField(max_length=255, unique=True)),
                ('maximun_ram_slot', models.IntegerField(blank=True, null=True)),
                ('pci', models.CharField(blank=True, max_length=255, null=True)),
                ('back_panel', models.CharField(blank=True, max_length=255, null=True)),
                ('chipset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.chipset')),
                ('cpu_support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer')),
                ('mainboard_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.mainboard_form')),
                ('ram_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ram_type')),
                ('socket_cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.socket_cpu')),
            ],
        ),
        migrations.CreateModel(
            name='Hard_Drive',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('name_hard_drive', models.CharField(max_length=255, unique=True)),
                ('capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('ssd', models.BooleanField(blank=True, default=False)),
                ('read_speed', models.IntegerField(blank=True, null=True)),
                ('write_speed', models.IntegerField(blank=True, null=True)),
                ('connection_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.connection_standard')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('name_cpu', models.CharField(max_length=255, unique=True)),
                ('cpu_type', models.CharField(max_length=50, unique=True)),
                ('number_of_core', models.IntegerField(blank=True, null=True)),
                ('number_of_threads', models.IntegerField(blank=True, null=True)),
                ('processing_speed', models.TextField(blank=True, null=True)),
                ('cache_cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('tdp', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.cpu_generation')),
                ('cpu_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cpu_series')),
                ('socket_cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.socket_cpu')),
            ],
        ),
        migrations.AddConstraint(
            model_name='socket_support',
            constraint=models.UniqueConstraint(fields=('radiator', 'socket_cpu'), name='unique_radiator_socketcpu_combination'),
        ),
        migrations.AddConstraint(
            model_name='mainboard_support',
            constraint=models.UniqueConstraint(fields=('case_cover', 'mainboard_form'), name='unique_casecover_mainboardform_combination'),
        ),
    ]
